version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    image: bandito-php
    container_name: bandito_php83
    user: "${HOST_UID}:${HOST_GID}"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ../app:/app
    working_dir: /app
    depends_on:
      - db

  nginx:
    image: nginx:stable
    container_name: bandito_nginx
    ports:
      - "9000:80"
    volumes:
      - ../app:/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: bandito
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
